# Generated by Django 3.0.8 on 2020-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprarArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=5000, null=True)),
                ('categoria', models.CharField(blank=True, choices=[('Cereal', 'Cereal'), ('Frutas', 'Fruta'), ('Verduras', 'Verdura'), ('Lácteos', 'Lácteos')], max_length=20, null=True)),
            ],
        ),
    ]
